ASTFClient get_profiles() is changed to getter.
cisco-system-traffic-generator/trex-core pull request #860
Opened 2022-05-26 05:14 UTC by jsmoon

Hi, this change is to solve issue #851.

From this change, ASTFClient get_profiles() returns the list of profiles from the server.

Please review my change.

2022-05-26 09:26 UTC, bdollma requested changes

2022-05-26 09:36 UTC, jsmoon commented on scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py
> +        return rc.data()
@bdollma I'm sorry it's due to unexpected patchwork. I'll change it and push again.

2022-05-26 11:11 UTC, bdollma approved these changes
Looks good.

2022-05-29 09:00 UTC, hhaim commented
rebased

2022-05-29 09:00 UTC, closed without merging